# Generated by Django 5.1.1 on 2024-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bugreport_coffeeshopapplication_menucategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
