# Generated by Django 5.1.1 on 2024-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_bio_alter_user_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_item_images/'),
        ),
        migrations.AddField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_images/'),
        ),
        migrations.AlterField(
            model_name='coffeeshopapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_shop_application_images/'),
        ),
    ]
